services:
  postgres:
    image: 'postgres:18.4-bookworm'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
      - 'TZ=UTC'
    ports:
      - '5432'
